version: '3.8'

services:
  app:
    image: node:14-alpine
    working_dir: /apps
    volumes:
      - .:/apps
    command: npm start
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./build:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - app
